-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:90b3b11fdfcb9816c6f59e1ef3c19f88$
-- 

return {
	texture = 'monster.png',
	frames = {
			{
				name = "foot_0.png",
				spriteColorRect = { x = 1, y = 8, width = 135, height = 147 },
				uvRect = { u0 = 0.0078125, v0 = 0.0566406, u1 = 0.294922, v1 = 0.188477 },
				spriteSourceSize = { width = 139, height = 159 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "foot_a.png",
				spriteColorRect = { x = 2, y = 10, width = 120, height = 146 },
				uvRect = { u0 = 0.302734, v0 = 0.0566406, u1 = 0.587891, v1 = 0.173828 },
				spriteSourceSize = { width = 134, height = 162 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "forearm_0.png",
				spriteColorRect = { x = 5, y = 5, width = 74, height = 94 },
				uvRect = { u0 = 0.699219, v0 = 0.454102, u1 = 0.882812, v1 = 0.526367 },
				spriteSourceSize = { width = 84, height = 108 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "forearm_a.png",
				spriteColorRect = { x = 5, y = 7, width = 89, height = 68 },
				uvRect = { u0 = 0.818359, v0 = 0.383789, u1 = 0.992188, v1 = 0.450195 },
				spriteSourceSize = { width = 99, height = 78 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hand_0_0.png",
				spriteColorRect = { x = 8, y = 14, width = 92, height = 75 },
				uvRect = { u0 = 0.0078125, v0 = 0.624023, u1 = 0.1875, v1 = 0.697266 },
				spriteSourceSize = { width = 110, height = 117 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hand_0_1.png",
				spriteColorRect = { x = 8, y = 14, width = 92, height = 75 },
				uvRect = { u0 = 0.199219, v0 = 0.550781, u1 = 0.378906, v1 = 0.624023 },
				spriteSourceSize = { width = 110, height = 117 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hand_0_2.png",
				spriteColorRect = { x = 7, y = 13, width = 94, height = 77 },
				uvRect = { u0 = 0.0078125, v0 = 0.544922, u1 = 0.191406, v1 = 0.620117 },
				spriteSourceSize = { width = 110, height = 117 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hand_0_3.png",
				spriteColorRect = { x = 8, y = 14, width = 96, height = 79 },
				uvRect = { u0 = 0.214844, v0 = 0.469727, u1 = 0.402344, v1 = 0.546875 },
				spriteSourceSize = { width = 110, height = 117 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hand_a_0.png",
				spriteColorRect = { x = 10, y = 11, width = 64, height = 91 },
				uvRect = { u0 = 0.863281, v0 = 0.291016, u1 = 0.988281, v1 = 0.379883 },
				spriteSourceSize = { width = 104, height = 113 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "hand_a_1.png",
				spriteColorRect = { x = 11, y = 11, width = 68, height = 93 },
				uvRect = { u0 = 0.410156, v0 = 0.514648, u1 = 0.591797, v1 = 0.581055 },
				spriteSourceSize = { width = 104, height = 113 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "hand_a_2.png",
				spriteColorRect = { x = 10, y = 7, width = 68, height = 97 },
				uvRect = { u0 = 0.501953, v0 = 0.444336, u1 = 0.691406, v1 = 0.510742 },
				spriteSourceSize = { width = 104, height = 113 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "hand_a_3.png",
				spriteColorRect = { x = 10, y = 7, width = 66, height = 97 },
				uvRect = { u0 = 0.863281, v0 = 0.192383, u1 = 0.992188, v1 = 0.287109 },
				spriteSourceSize = { width = 104, height = 113 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "head_0.png",
				spriteColorRect = { x = 1, y = 7, width = 128, height = 131 },
				uvRect = { u0 = 0.554688, v0 = 0.31543, u1 = 0.810547, v1 = 0.44043 },
				spriteSourceSize = { width = 144, height = 151 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "head_1.png",
				spriteColorRect = { x = 7, y = 6, width = 122, height = 135 },
				uvRect = { u0 = 0.591797, v0 = 0.192383, u1 = 0.855469, v1 = 0.311523 },
				spriteSourceSize = { width = 144, height = 151 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "head_2.png",
				spriteColorRect = { x = 7, y = 6, width = 122, height = 133 },
				uvRect = { u0 = 0.0078125, v0 = 0.28418, u1 = 0.267578, v1 = 0.40332 },
				spriteSourceSize = { width = 144, height = 151 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "head_3.png",
				spriteColorRect = { x = 7, y = 8, width = 122, height = 133 },
				uvRect = { u0 = 0.287109, v0 = 0.245117, u1 = 0.546875, v1 = 0.364258 },
				spriteSourceSize = { width = 144, height = 151 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "pelvis_0.png",
				spriteColorRect = { x = 8, y = 10, width = 90, height = 139 },
				uvRect = { u0 = 0.0078125, v0 = 0.192383, u1 = 0.279297, v1 = 0.280273 },
				spriteSourceSize = { width = 110, height = 149 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "shadow_idle.png",
				spriteColorRect = { x = 3, y = 4, width = 315, height = 50 },
				uvRect = { u0 = 0.0078125, v0 = 0.00390625, u1 = 0.623047, v1 = 0.0527344 },
				spriteSourceSize = { width = 321, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "shoulder_0.png",
				spriteColorRect = { x = 6, y = 6, width = 102, height = 78 },
				uvRect = { u0 = 0.0078125, v0 = 0.464844, u1 = 0.207031, v1 = 0.541016 },
				spriteSourceSize = { width = 114, height = 94 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "shoulder_a.png",
				spriteColorRect = { x = 6, y = 3, width = 55, height = 105 },
				uvRect = { u0 = 0.0078125, v0 = 0.407227, u1 = 0.212891, v1 = 0.460938 },
				spriteSourceSize = { width = 71, height = 115 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "thigh_0.png",
				spriteColorRect = { x = 8, y = 4, width = 65, height = 144 },
				uvRect = { u0 = 0.302734, v0 = 0.177734, u1 = 0.583984, v1 = 0.241211 },
				spriteSourceSize = { width = 81, height = 156 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "thigh_a.png",
				spriteColorRect = { x = 4, y = 2, width = 112, height = 100 },
				uvRect = { u0 = 0.275391, v0 = 0.368164, u1 = 0.494141, v1 = 0.46582 },
				spriteSourceSize = { width = 126, height = 112 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "torso_0.png",
				spriteColorRect = { x = 0, y = 8, width = 180, height = 189 },
				uvRect = { u0 = 0.630859, v0 = 0.00390625, u1 = 0.982422, v1 = 0.188477 },
				spriteSourceSize = { width = 180, height = 197 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

